# Experiment Configuration
experiment:
  name: "ANYFMTX_R2_Geometric_Test"
  planner_type: "KinodynamicANYFMTX"
  state_space_type: "RDT"
  manager_type: "R2T" # Or "R2" if you have a specific geometric manager

# Simulation Settings
simulation:
  time_budget: 0.0 # Not used in geometric mode
  duration_limit: 10
  slice_time: 0.05 # Geometric updates can be slower
  seed: 42

# Robot & State Space Definition
robot:
  # Start: x, y (No time)
  start_state: [48.0, 48.0] 
  # Goal: x, y (No time)
  goal_state:  [-48.0, -48.0]
  
  dimensions: 2
  spatial_dim: 2
  bounds_min: [-50.0, -50.0]
  bounds_max: [50.0, 50.0]
  
  # Dynamics (Used for sampling speed, but not integration)
  min_velocity: 0.0
  max_velocity: 20.0
  robot_velocity: 10.0

# Planner Parameters
planner_params:
  num_of_samples: 100
  factor: 2.0
  delta: 25.0
  epsilon: 0.1
  # epsilon: 0.0
  partial_plot: "true" 
  static_obs_presence: "true"
  obs_cache: "false"
  use_kdtree: true
  kdtree_type: "NanoFlann"
  partial_update: false
  kd_dim: 2 # 2 for R2
  precache_neighbors: true
  use_heuristic: false
  is_geometric_mode: true # Important flag for your planner

# Manager / Gazebo Parameters
manager_params:
  use_sim_time: true
  sim_time_step: -0.04
  sim_frequency_hz: 50
  vis_frequency_hz: 30
  follow_path: false # False for geometric (we don't move the robot sim)
  inflation: 0.0

gazebo_params:
  robot_model_name: "tugbot"
  world_name: "default"
  sdf_path: "/home/sohail/gazeb/GAZEBO_MOV/dynamic_world_1_obs.sdf"
  inflation: 0.0
  default_robot_x: 48.0  
  default_robot_y: 48.0
  use_range: false
  sensor_range: 20.0
  estimation: true
  kf_model_type: "cv"
  fcl: false
  bullet: false
  persistent_static_obstacles: false
  is_geometric_mode: true
