experiment:
  name: "ANYFMTX_R2T_Test"
  planner_type: "KinodynamicANYFMTX" # Maps to PlannerType enum
  state_space_type: "RDT"
  manager_type: "R2T"

simulation:
  time_budget: 25.0
  slice_time: 0.02
  seed: 42

robot:
  start_state: [48.0, 48.0] # x, y, time_budget
  goal_state:  [-48.0, -48.0] # x, y, time_to_go
  dimensions: 3
  bounds_min: [-50.0, -50.0]
  bounds_max: [50.0, 50.0]
  min_velocity: 0.0
  max_velocity: 20.0

planner_params:
  num_of_samples: 1
  factor: 2.0
  delta: 20.0
  epsilon: 0.0
  kdtree_type: "NanoFlann"
  partial_update: true
  kd_dim: 3
  is_geometric_mode: false
  num_pillar_nodes: 0
  goal_radius: 0.5


manager_params:
  vis_frequency_hz: 30

gazebo_params:
  sdf_path: "../sims/dynamic_world_straight_box_circle_10.sdf"
  inflation: 0.75