experiment:
  name: "ANYFMTX_Thruster_Test"
  planner_type: "KinodynamicANYFMTX"
  state_space_type: "Thruster"
  manager_type: "Thruster"

simulation:
  time_budget: 35.0
  slice_time: 0.02
  seed: 44

robot:
  start_state: [48.0, 48.0, 0.0, 0.0]
  goal_state:  [-48.0, -48.0, 0.0, 0.0]
  dimensions: 5
  bounds_min: [-50.0, -50.0, -10.0, -10.0]
  bounds_max: [ 50.0,  50.0,  10.0,  10.0]
  min_velocity: 0.0
  max_velocity: 10.0
  max_acceleration: 5.0

planner_params:
  num_of_samples: 1
  factor: 3.0
  delta: 45.0
  epsilon: 0.1
  kdtree_type: "NanoFlann"
  partial_update: true
  kd_dim: 5
  is_geometric_mode: false
  num_pillar_nodes: 0
  goal_radius: 0.5

manager_params:
  vis_frequency_hz: 30

gazebo_params:
  sdf_path: "../sims/dynamic_world_straight_box_circle_20_thruster.sdf"
  # sdf_path: "../sims/dynamic_world_4_obs.sdf"
  # sdf_path: "../sims/dynamic_world_diag.sdf"
  # sdf_path: "../sims/static_world_straight_box_circle_35.sdf"
  # sdf_path: "../sims/static_dynamic_world_straight_box_circle.sdf"
  # sdf_path: "../sims/static_dynamic_world_straight_box_circle_11.sdf"
  inflation: 1.0