experiment:
  name: "PRMSTARDSTARLITE_Dubins_Test"
  planner_type: "KinodynamicPRMStarDStarLite"
  state_space_type: "Dubins"
  manager_type: "Dubins"

simulation:
  time_budget: 40.0
  slice_time: 0.02
  seed: 42

robot:
  start_state: [48.0, 48.0, -0.785] # x, y, theta, time_budget
  goal_state:  [-48.0, -48.0, -2.356] # x, y, theta, time_to_go
  dimensions: 4
  bounds_min: [-50.0, -50.0, -3.14159]
  bounds_max: [50.0, 50.0, 3.14159]
  
  min_velocity: 2.0
  max_velocity: 20.0
  min_turning_radius: 2.0

planner_params:
  num_of_samples: 2000
  factor: 3.0
  kdtree_type: "NanoFlann"
  partial_update: false
  kd_dim: 4
  is_geometric_mode: false
  num_pillar_nodes: 50
  goal_radius: 0.5

manager_params:
  vis_frequency_hz: 30

gazebo_params:
  sdf_path: "../sims/dynamic_world_straight_box_circle_10.sdf"
  inflation: 0.75