experiment:
  name: "FMTX_R2_Geometric_Test"
  planner_type: "KinodynamicFMTX"
  state_space_type: "RDT"
  manager_type: "R2T"

simulation:
  duration_limit: 5
  slice_time: 0.05
  seed: 42

robot:
  start_state: [48.0, 48.0] 
  goal_state:  [-48.0, -48.0]
  dimensions: 2
  bounds_min: [-50.0, -50.0]
  bounds_max: [50.0, 50.0]

planner_params:
  num_of_samples: 1000
  factor: 2.0
  kdtree_type: "NanoFlann"
  partial_update: false
  kd_dim: 2 # 2 for R2
  is_geometric_mode: true

manager_params:
  vis_frequency_hz: 30

gazebo_params:
  # sdf_path: "../sims/dynamic_world_straight_box_circle_20.sdf"
  sdf_path: "../sims/dynamic_world_1_obs.sdf"
  inflation: 0.0